### ISSUE TITLE
Operators for MongoDB/BSON numeric types

### ISSUE THREAD

**Issue by devkev** [rueckstiess/mgeneratejs#4]
eg. `$numberInt`, `$numberLong`, `$numberDecimal`

Looks like these are the main things from the [BSON spec](http://bsonspec.org/spec.html) which are missing in mgenerate.js.  They would vaguely work like `change.integer()`, and/or maybe also `change.dollar()` for `$numberDecimal`.

Code is also missing (but it's very infrequently encountered).  So are deprecated BSON types like DBPointer/DBRef, Symbol, and undefined (but being deprecated, they don't really matter).

**Comment by rueckstiess** [comment]
Those are already there, just not documented yet. Adding to README now.

**Comment by rueckstiess** [comment]
Hi @taatuut,

Thanks for reporting this. Initially I didn't add a `$numberInt` operator, because `$number` / `$integer` already exist in chance.js and can be used. But I realised they are actually producing numbers between -2^53 and +2^53-1 (Biggest number in Javascript). 

To clean up this mess and make it more compatible with what MongoDB does, I did the following: 

- Changed the behaviour of `$number` / `$integer` to return a 32-bit integer with value between -2^31 and +2^31-1. 
- Added another alias `$numberInt` to map to `$integer`. 
- Added this to the documentation here: https://github.com/rueckstiess/mgeneratejs#numberint

You can get the latest version by upgrading to 0.6 via `npm update -g mgeneratejs`. 

Hope that solves this issue.

**Comment by taatuut** [comment]
Hi @rueckstiess, thanks for the quick action, works without issues now!
